---
# TensorRT configuration
tensorrt_version: "8.6.1.6"
tensorrt_cuda_version: "12.0"

# cuDNN configuration
cudnn_version: "8.9.7.29"

# Installation options
tensorrt_install_devel: true
tensorrt_verify_installation: true
tensorrt_hold_packages: true

# Runtime packages
tensorrt_runtime_packages:
  - "libcudnn8={{ cudnn_version }}"
  - "libnvinfer10={{ tensorrt_version }}"
  - "libnvinfer-plugin10={{ tensorrt_version }}"
  - "libnvonnxparsers10={{ tensorrt_version }}"

# Development packages
tensorrt_dev_packages:
  - "libcudnn8-dev={{ cudnn_version }}"
  - "libnvinfer-dev={{ tensorrt_version }}"
  - "libnvinfer-plugin-dev={{ tensorrt_version }}"
  - "libnvinfer-headers-dev={{ tensorrt_version }}"
  - "libnvinfer-headers-plugin-dev={{ tensorrt_version }}"
  - "libnvonnxparsers-dev={{ tensorrt_version }}"

# Package hold list
tensorrt_hold_runtime_packages:
  - libcudnn8
  - libnvinfer10
  - libnvinfer-plugin10
  - libnvonnxparsers10

tensorrt_hold_dev_packages:
  - libcudnn8-dev
  - libnvinfer-dev
  - libnvinfer-plugin-dev
  - libnvinfer-headers-dev
  - libnvinfer-headers-plugin-dev
  - libnvonnxparsers-dev
