extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: disable
  
  # Allow both true/false and yes/no
  truthy:
    check-keys: false
  
  # Allow comments
  comments-indentation: disable
  
  # Allow trailing spaces in some cases
  trailing-spaces: disable
  
  # Allow empty lines at the end of files
  empty-lines:
    max: 1
    max-end: 1
