/**:
  ntrip_client:
    ros__parameters:

      host: ntrip.hi-rtk.io
      port: 2101
      mountpoint: SNS_AUTO
      username: sns
      password: "1234"

      ntrip_version: 'NTRIP/2.0'
      ntrip_server_hz: 1.0
      authenticate: True

      ssl: false
      cert: None
      key: None
      ca_cert: None
      rtcm_frame_id: 'rtcm'
      nmea_max_length: 500
      nmea_min_length: 3
      rtcm_message_package: 'rtcm_msgs'
      reconnect_attempt_max: 10
      reconnect_attempt_wait_seconds: 5
      rtcm_timeout_seconds: 10