/**:
  um982_node:
    ros__parameters:
    
      port:
        gnss: /dev/UM982
        gnss_baudrate: 115200
        rtcm: /dev/UM982-RTCM
        rtcm_baudrate: 115200

      frame_id: gps_left_link
      
      # horizontal setup
      heading_offset: 1.57

      heading_system: 'enu'
      
      publish:
        nmea: true

      verbose: true