- name: Install cuDNN and TensorRT runtime packages
  become: true
  ansible.builtin.apt:
    name:
      - "libcudnn8={{ cudnn_version }}"
      - "libnvinfer10={{ tensorrt_version }}"
      - "libnvinfer-plugin10={{ tensorrt_version }}"
      - "libnvonnxparsers10={{ tensorrt_version }}"
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: true

- name: Install cuDNN and TensorRT development packages
  become: true
  ansible.builtin.apt:
    name:
      - "libcudnn8-dev={{ cudnn_version }}"
      - "libnvinfer-dev={{ tensorrt_version }}"
      - "libnvinfer-plugin-dev={{ tensorrt_version }}"
      - "libnvinfer-headers-dev={{ tensorrt_version }}"
      - "libnvinfer-headers-plugin-dev={{ tensorrt_version }}"
      - "libnvonnxparsers-dev={{ tensorrt_version }}"
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: false
  when: install_devel == 'y'

# apt-mark hold (optional for stability)
- name: Prevent TensorRT runtime packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - libcudnn8
    - libnvinfer10
    - libnvinfer-plugin10
    - libnvonnxparsers10
  when: tensorrt_hold_packages | default(true) | bool

- name: Prevent TensorRT development packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - libcudnn8-dev
    - libnvinfer-dev
    - libnvinfer-plugin-dev
    - libnvinfer-headers-dev
    - libnvinfer-headers-plugin-dev
    - libnvonnxparsers-dev
  when: install_devel == 'y' and tensorrt_hold_packages | default(true) | bool

# Verification tasks removed for faster builds - packages will fail if installation doesn't work