- name: Set up source development environments for mowbot
  hosts: localhost
  connection: local
  vars_prompt:
    - name: prompt_install_nvidia
      prompt: |-
        [Warning] Some Mowbot components depend on the CUDA, cuDNN and TensorRT NVIDIA libraries which have end-user license agreements that should be reviewed before installation.
        Install NVIDIA libraries? [y/N]
      private: false
    - name: prompt_download_artifacts
      prompt: |-
        [Warning] Should the ONNX model files and other artifacts be downloaded alongside setting up the development environment.
        Download artifacts? [y/N]
      private: false
    - name: install_devel
      prompt: |-
        [Warning] Do you want to install recommended development tools for Mowbot? [y/N]
      private: false
      default: y

  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 is supported for this branch.
      when: ansible_distribution_version != '22.04'

    - name: Print configuration
      ansible.builtin.debug:
        msg:
          - "ROS 2 Distribution: {{ rosdistro | default('humble') }}"
          - "RMW Implementation: {{ rmw_implementation | default('rmw_cyclonedds_cpp') }}"
          - "CUDA Version: {{ cuda_version | default('12.4') }}"
          - "cuDNN Version: {{ cudnn_version | default('8.9.7.29') }}"
          - "TensorRT Version: {{ tensorrt_version | default('8.6.1.6') }}"
          - "Install NVIDIA: {{ prompt_install_nvidia | default('N') }}"
          - "Download Artifacts: {{ prompt_download_artifacts | default('N') }}"
          - "Install Dev Tools: {{ install_devel | default('y') }}"

    - name: Show a warning if the NVIDIA libraries will not be installed
      ansible.builtin.pause:
        seconds: 10
        prompt: |
          [Warning] Skipping installation of NVIDIA libraries. Please manually install them if you plan to use any dependent components.
      when: prompt_install_nvidia != 'y'

  roles:
    # Core development environment (always installed)
    - role: mowbot.dev_env.build_tools
    - role: mowbot.dev_env.geographiclib
    - role: mowbot.dev_env.rmw_implementation

    # GPU acceleration (conditional)
    - role: mowbot.dev_env.cuda
      when: prompt_install_nvidia == 'y'
    - role: mowbot.dev_env.tensorrt
      when: prompt_install_nvidia == 'y'
    - role: mowbot.dev_env.nvidia_container_toolkit
      when: prompt_install_nvidia == 'y'
    - role: mowbot.dev_env.kisak_mesa
      when: prompt_install_nvidia == 'y'

    # Development tools (conditional)
    - role: mowbot.dev_env.dev_tools
      when: install_devel == 'y'
  
    # Artifacts and assets (conditional)
    - role: mowbot.dev_env.artifacts
      when: prompt_download_artifacts == 'y'