- name: Install build tools
  become: true
  ansible.builtin.apt:
    name:
      - ccache
      - build-essential
      - cmake
      - ninja-build
      - pkg-config
    state: latest
    update_cache: true

- name: Add CCACHE_DIR to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "export CCACHE_DIR={{ ccache_dir }}"
    state: present
    create: true
    mode: 0644

- name: Add CCACHE_DIR to .bashrc of local user
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/skel/.bashrc
    line: export CCACHE_DIR="$HOME/.ccache"
    state: present
    create: true
    mode: 0644

- name: Export CC to ccache
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export CC="/usr/lib/ccache/gcc"
    state: present
    create: true
    mode: 0644

- name: Export CXX to ccache
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export CXX="/usr/lib/ccache/g++"
    state: present
    create: true
    mode: 0644

- name: Create ccache directory
  ansible.builtin.file:
    path: "{{ ccache_dir }}"
    state: directory
    mode: 0755

- name: Configure ccache max size
  ansible.builtin.shell: ccache -M {{ ccache_max_size }}
  changed_when: false