

- name: Add NVIDIA container toolkit GPG key
  become: true
  ansible.builtin.apt_key:
    url: "{{ nvidia_container_toolkit_gpg_url }}"
    state: present
    keyring: "{{ nvidia_container_toolkit_keyring }}"

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: system_architecture
  changed_when: false

- name: Add NVIDIA container toolkit repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ nvidia_container_toolkit_keyring }}] {{ nvidia_container_toolkit_repo_url }}/{{ system_architecture.stdout }} /"
    state: present
    filename: "{{ nvidia_container_toolkit_repo_filename }}"
    update_cache: true

- name: Install NVIDIA Container Toolkit
  become: true
  ansible.builtin.apt:
    name: "{{ nvidia_container_toolkit_packages }}"
    update_cache: true
  register: nvidia_container_installation

- name: Add NVIDIA runtime support to docker engine
  become: true
  ansible.builtin.shell: |
    nvidia-ctk runtime configure --runtime={{ nvidia_container_toolkit_runtime }}
  changed_when: true
  register: nvidia_runtime_config

- name: Restart docker daemon
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
  changed_when: true
  when: nvidia_container_toolkit_restart_docker | bool

- name: Verify NVIDIA Container Toolkit installation
  ansible.builtin.command: nvidia-ctk --version
  changed_when: false
  failed_when: false
  register: nvidia_ctk_verification
  when: nvidia_container_toolkit_verify_installation | bool

- name: Display NVIDIA Container Toolkit version
  ansible.builtin.debug:
    msg: "✅ NVIDIA Container Toolkit installed: {{ nvidia_ctk_verification.stdout }}"
  when: nvidia_container_toolkit_verify_installation | bool and nvidia_ctk_verification.rc == 0

- name: Display NVIDIA Container Toolkit installation warning
  ansible.builtin.debug:
    msg: "⚠️ Warning: NVIDIA Container Toolkit may not be properly installed. Check manually if needed."
  when: nvidia_container_toolkit_verify_installation | bool and nvidia_ctk_verification.rc != 0

- name: Test NVIDIA Container Toolkit with CUDA container
  become: true
  ansible.builtin.docker_container:
    name: nvidia-test
    image: nvcr.io/nvidia/cuda:12.3.1-runtime-ubuntu20.04
    command: nvidia-smi
    auto_remove: true
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
  when: nvidia_container_toolkit_test_installation | bool and nvidia_ctk_verification.rc == 0 and not (ansible_env.MOWBOT_DISABLE_DOCKER_RESTART is defined and ansible_env.MOWBOT_DISABLE_DOCKER_RESTART == "true")
  register: nvidia_test_result

- name: Display NVIDIA Container Toolkit test result
  ansible.builtin.debug:
    msg: "✅ NVIDIA Container Toolkit test successful - GPU access working"
  when: nvidia_container_toolkit_test_installation | bool and nvidia_test_result is defined and nvidia_test_result.changed and not (ansible_env.MOWBOT_DISABLE_DOCKER_RESTART is defined and ansible_env.MOWBOT_DISABLE_DOCKER_RESTART == "true")

- name: Display NVIDIA Container Toolkit test warning
  ansible.builtin.debug:
    msg: "⚠️ Warning: NVIDIA Container Toolkit test failed. Check GPU drivers and Docker configuration."
  when: nvidia_container_toolkit_test_installation | bool and nvidia_test_result is defined and not nvidia_test_result.changed and not (ansible_env.MOWBOT_DISABLE_DOCKER_RESTART is defined and ansible_env.MOWBOT_DISABLE_DOCKER_RESTART == "true")