name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'ansible/**'
      - 'setup-dev-env.sh'
      - '*.env'
      - 'ansible-galaxy-requirements.yaml'
      - 'mowbot.repos'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'ansible/**'
      - 'setup-dev-env.sh'
      - '*.env'
      - 'ansible-galaxy-requirements.yaml'
      - 'mowbot.repos'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # Use short SHA for versioning
  VERSION: ${{ github.sha }}

jobs:
  build-images:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Reduced timeout
    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0
          buildkitd-flags: --debug

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          # Start SSH agent and add key (official Docker solution)
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          
          # Export SSH_AUTH_SOCK for Docker builds
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          
          # Test SSH connection
          ssh -T git@github.com || true
          
          echo "SSH setup completed!"

      - name: Configure Docker Buildx SSH
        run: |
          # Ensure SSH agent is running and key is loaded
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          
          # Configure Docker Buildx with SSH agent
          docker buildx create --use --name builder-with-ssh --driver docker-container
          
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
          echo "SSH agent configured for Docker Buildx"

      - name: Verify SSH agent for Docker
        run: |
          # Ensure SSH agent is available for Docker builds
          if [ -n "$SSH_AUTH_SOCK" ] && [ -S "$SSH_AUTH_SOCK" ]; then
            echo "SSH agent socket exists and is accessible"
            ls -la "$SSH_AUTH_SOCK"
          else
            echo "ERROR: SSH agent socket not found or not accessible"
            exit 1
          fi
          
          # Test SSH agent with Docker
          docker run --rm -e SSH_AUTH_SOCK="$SSH_AUTH_SOCK" -v "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK" alpine:latest sh -c "apk add --no-cache openssh-client && ssh-add -l" || echo "SSH agent test completed"

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Install vcstool
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install vcstool

      - name: Clean up any Git lock files
        run: |
          echo "Cleaning up any leftover Git lock files..."
          find . -name ".git/index.lock" -delete 2>/dev/null || true
          find . -name ".git/HEAD.lock" -delete 2>/dev/null || true
          find . -name ".git/refs/heads/*.lock" -delete 2>/dev/null || true
          find . -name ".git/refs/tags/*.lock" -delete 2>/dev/null || true
          find . -name ".git/MERGE_HEAD.lock" -delete 2>/dev/null || true
          find . -name ".git/MERGE_MODE.lock" -delete 2>/dev/null || true
          find . -name ".git/MERGE_MSG.lock" -delete 2>/dev/null || true
          echo "Git lock cleanup completed!"

      - name: Configure Git for private repositories
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          export GIT_TERMINAL_PROMPT=0
          echo "Git configuration completed successfully!"

      - name: Clean up disk space before build
        run: |
          echo "Cleaning up disk space before build..."
          docker system prune -af --volumes
          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
          df -h
          echo "Disk cleanup completed!"

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Ensure SSH agent is available
        run: |
          # Ensure SSH agent is running and key is loaded before builds
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          
          # Verify SSH agent is working
          ssh-add -l
          echo "SSH agent is ready for Docker builds"

      - name: Build and push base images (parallel)
        run: |
          cd docker
          chmod +x build.sh
          
          echo "Building base images in parallel..."
          
          # Build base for both platforms in parallel
          (./build.sh --target base --platform linux/amd64 --version $VERSION && \
           docker tag ghcr.io/serene4mr/mowbot:base ghcr.io/serene4mr/mowbot:base-amd64 && \
           docker push ghcr.io/serene4mr/mowbot:base-amd64) &
          
          (./build.sh --target base --platform linux/arm64 --version $VERSION && \
           docker push ghcr.io/serene4mr/mowbot:base-arm64) &
          
          # Wait for both builds to complete
          wait
          
          # Clean up after base builds
          docker system prune -af --volumes
          sudo apt-get clean
          sudo apt-get autoremove -y
          df -h
          
          # Create multi-arch manifest for base
          docker manifest create ghcr.io/serene4mr/mowbot:base \
            ghcr.io/serene4mr/mowbot:base-amd64 \
            ghcr.io/serene4mr/mowbot:base-arm64
          docker manifest push ghcr.io/serene4mr/mowbot:base
          
          # Also tag as latest
          docker manifest create ghcr.io/serene4mr/mowbot:base-latest \
            ghcr.io/serene4mr/mowbot:base-amd64 \
            ghcr.io/serene4mr/mowbot:base-arm64
          docker manifest push ghcr.io/serene4mr/mowbot:base-latest

      - name: Build and push main-dev images (parallel)
        run: |
          cd docker
          
          echo "Building main-dev images in parallel..."
          
          # Build main-dev for both platforms in parallel
          (./build.sh --target main-dev --platform linux/amd64 --version $VERSION && \
           docker tag ghcr.io/serene4mr/mowbot:main-dev ghcr.io/serene4mr/mowbot:main-dev-amd64 && \
           docker push ghcr.io/serene4mr/mowbot:main-dev-amd64) &
          
          (./build.sh --target main-dev --platform linux/arm64 --version $VERSION && \
           docker push ghcr.io/serene4mr/mowbot:main-dev-arm64) &
          
          # Wait for both builds to complete
          wait
          
          # Clean up after main-dev builds
          docker system prune -af --volumes
          sudo apt-get clean
          sudo apt-get autoremove -y
          df -h
          
          # Create multi-arch manifest for main-dev
          docker manifest create ghcr.io/serene4mr/mowbot:main-dev \
            ghcr.io/serene4mr/mowbot:main-dev-amd64 \
            ghcr.io/serene4mr/mowbot:main-dev-arm64
          docker manifest push ghcr.io/serene4mr/mowbot:main-dev
          
          # Also tag as latest
          docker manifest create ghcr.io/serene4mr/mowbot:main-dev-latest \
            ghcr.io/serene4mr/mowbot:main-dev-amd64 \
            ghcr.io/serene4mr/mowbot:main-dev-arm64
          docker manifest push ghcr.io/serene4mr/mowbot:main-dev-latest

      - name: Build and push CUDA images
        run: |
          cd docker
          
          echo "Building CUDA images (AMD64 only)..."
          
          # Clean up before CUDA build (CUDA builds are very large)
          docker system prune -af --volumes
          sudo apt-get clean
          sudo apt-get autoremove -y
          df -h
          
          # Build main-dev-cuda for AMD64 only
          ./build.sh --target main-dev-cuda --platform linux/amd64 --version $VERSION
          docker push ghcr.io/serene4mr/mowbot:main-dev-cuda
          
          # Also tag as latest
          docker tag ghcr.io/serene4mr/mowbot:main-dev-cuda ghcr.io/serene4mr/mowbot:main-dev-cuda-latest
          docker push ghcr.io/serene4mr/mowbot:main-dev-cuda-latest

      - name: Final cleanup
        if: always()
        run: |
          docker system prune -af --volumes
          echo "✅ All Docker images built and pushed successfully!"

      - name: Summary
        if: success()
        run: |
          echo "🎉 Build Summary:"
          echo "✅ Base images: ghcr.io/serene4mr/mowbot:base (multi-arch)"
          echo "✅ Main-dev images: ghcr.io/serene4mr/mowbot:main-dev (multi-arch)"
          echo "✅ CUDA images: ghcr.io/serene4mr/mowbot:main-dev-cuda (AMD64)"
          echo "✅ All images tagged with: $VERSION and latest"
          echo ""
          echo "📦 Available images:"
          echo "  - ghcr.io/serene4mr/mowbot:base"
          echo "  - ghcr.io/serene4mr/mowbot:base-latest"
          echo "  - ghcr.io/serene4mr/mowbot:main-dev"
          echo "  - ghcr.io/serene4mr/mowbot:main-dev-latest"
          echo "  - ghcr.io/serene4mr/mowbot:main-dev-cuda"
          echo "  - ghcr.io/serene4mr/mowbot:main-dev-cuda-latest"
