name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'ansible/**'
      - 'setup-dev-env.sh'
      - '*.env'
      - 'ansible-galaxy-requirements.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'ansible/**'
      - 'setup-dev-env.sh'
      - '*.env'
      - 'ansible-galaxy-requirements.yaml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base images
        run: |
          cd docker
          chmod +x build.sh
          ./build.sh --target base --platform linux/amd64
          ./build.sh --target base --platform linux/arm64
          ./build.sh --target base-cuda --platform linux/amd64

      - name: Build and push main images
        run: |
          cd docker
          ./build.sh --target main-dev --platform linux/amd64
          ./build.sh --target main-dev --platform linux/arm64
          ./build.sh --target main --platform linux/amd64
          ./build.sh --target main --platform linux/arm64

      - name: Build and push CUDA images
        run: |
          cd docker
          ./build.sh --target main-dev-cuda --platform linux/amd64
          ./build.sh --target main-cuda --platform linux/amd64
